name: Docker Image Prepare

on:
  workflow_run:
    workflows:
      - "SonarQube Scan"
    types:
      - completed

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=notebook
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-6)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Step 4: Push to Amazon ECR
      - name: Push to Amazon ECR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.ECR_URI }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.ECR_URI }}/$IMAGE_NAME:$IMAGE_TAG
