name: Docker Image Prepare

on:
  workflow_run:
    workflows:
      - "SonarQube Scan"
    types:
      - completed

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          
      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=notebook
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-6)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Step 5: Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo "Adding Trivy to PATH"
          export PATH=$PATH:./bin
          trivy --version

      # Step 6: Scan the Docker image with Trivy
      - name: Scan Docker Image with Trivy
        run: |
          IMAGE_NAME=notebook
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-6)
          echo "Scanning Docker image: $IMAGE_NAME:$IMAGE_TAG"
          ./bin/trivy image $IMAGE_NAME:$IMAGE_TAG

      # Step 7: Push to Amazon ECR
      - name: Push to Amazon ECR
        run: |
          IMAGE_NAME=notebook
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-6)
          docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.ECR_URI }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_URI }}:$IMAGE_TAG
