on:
  workflow_run:
    workflows:
      - "Docker Image Prepare"
    types:
      - completed

jobs:
  update-kustomization:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Step 2: Checkout the target repository
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: tramcandoit/notebook-manifests # Replace with the target repository
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # GitHub PAT with write access

      # Step 3: Install kustomize
      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          mv kustomize /usr/local/bin/

      # Step 4: Update kustomization.yaml using kustomize
      - name: Set image with kustomize
        run: |
          cd notebook
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-6)
          kustomize edit set image ${{ secrets.ECR_URI }}=${{ secrets.ECR_URI }}:${IMAGE_TAG}

      # Step 5: Commit changes
      - name: Commit changes
        run: |
          cd notebook
          git config user.name "${{ secrets.USER_NAME}}"
          git config user.email "${{ secrets.EMAIL }}"
          git add kustomization.yaml
          git commit -m "Update kustomization.yaml to use image tag ${GITHUB_SHA::6}" || echo "No changes to commit"

      # Step 6: Push changes
      - name: Push changes
        run: |
          cd notebook
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
